#version: '3.8'
name: python-robot

services:
  app:
    build: .
    image: python-robot:v1.0
    container_name: python-robot
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/Documents:/data/documents
      - ./monitor:/app/monitor
    # 容器内的环境变量配置文件
    environment:
      - TASK_FILE=/data/documents/工作任务.txt
      - CONFIG_PATH=/app/config.yaml
    ports:
      - "5000:5000"
    restart: unless-stopped
